# Generated by Django 5.2.8 on 2025-11-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='sala_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
